### ISSUE TITLE
rexpect 0.3 ready ? 

### ISSUE THREAD

**Issue by tjyang** [philippkeller/rexpect#3]
Hi @philippkeller 
In [README.md](https://github.com/philippkeller/rexpect/blob/master/README.md), the example is referring to rexpect 0.3.0 while the version on crates.io is only upto 0.2.0.

I tried to test out the examples in README.md using 0.2.0  but failed with following message.

```
[me@fedora01 src]$cargo build
   Compiling cmd1 v0.1.0 (file:///home/tjyang/cmd1)
error[E0061]: this function takes 1 parameter but 2 parameters were supplied
 --> src/main.rs:8:7
  |
8 |     p.execute("ping 8.8.8.8", "bytes of data")?;
  |       ^^^^^^^ expected 1 parameter

error[E0061]: this function takes 1 parameter but 2 parameters were supplied
  --> src/main.rs:12:7
   |
12 |     p.execute("bg", "ping 8.8.8.8")?;
   |       ^^^^^^^ expected 1 parameter

error[E0061]: this function takes 1 parameter but 2 parameters were supplied
  --> src/main.rs:17:7
   |
17 |     p.execute("fg", "ping 8.8.8.8")?;
   |       ^^^^^^^ expected 1 parameter

error: aborting due to 3 previous errors

error: Could not compile `cmd1`.

To learn more, run the command again with --verbose.
[me@fedora01 src]$

```

**Comment by philippkeller** [comment]
thanks for waking up this project again :+1: 
I added the second parameter on git master, but then forgot to publish it to crates.io. I now just pushed version 0.3 out. I tested it with a sample project and it worked for me. Can you try again with version 0.3?

**Comment by tjyang** [comment]
Hi @philippkeller 
No, I should thank you created rexpect at first place.  
I was able to cargo build and run the examples.

But I was not able to pass all the test cases.
```
[tjyang@fedora01 rexpect]$ RUST_BACKTRACE=1 cargo test
    Finished dev [unoptimized + debuginfo] target(s) in 0.0 secs
     Running target/debug/deps/rexpect-cb9c6d7dc7953d27

running 16 tests
test reader::tests::test_nbytes ... ok
test reader::tests::test_eof ... ok
test process::tests::test_cat ... ok
test reader::tests::test_regex ... ok
test reader::tests::test_regex2 ... ok
test reader::tests::test_try_read ... ok
test reader::tests::test_expect_melon ... ok
test session::tests::test_expect_any ... ok
test session::tests::test_bash ... FAILED
test session::tests::test_bash_control_chars ... ok
test session::tests::test_expect_string ... ok
test session::tests::test_expect_eof_timeout ... ok
test session::tests::test_read_line ... ok
test session::tests::test_expect_eof_timeout2 ... ok
test session::tests::test_read_string_before ... ok
test session::tests::test_kill_timeout ... ok

failures:

---- session::tests::test_bash stdout ----
        thread 'session::tests::test_bash' panicked at 'assertion failed: `(left == right)`
  left: `"/tmp\r\n"`,
 right: `"/tmp\r\n\u{1b}]0;tjyang@fedora01:/tmp\u{7}"`', src/session.rs:446:13
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at /checkout/src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::print
             at /checkout/src/libstd/sys_common/backtrace.rs:68
             at /checkout/src/libstd/sys_common/backtrace.rs:57
   2: std::panicking::default_hook::{{closure}}
             at /checkout/src/libstd/panicking.rs:381
   3: std::panicking::default_hook
             at /checkout/src/libstd/panicking.rs:391
   4: std::panicking::rust_panic_with_hook
             at /checkout/src/libstd/panicking.rs:577
   5: std::panicking::begin_panic
             at /checkout/src/libstd/panicking.rs:538
   6: std::panicking::begin_panic_fmt
             at /checkout/src/libstd/panicking.rs:522
   7: rexpect::session::tests::test_bash::{{closure}}
             at src/session.rs:446
   8: rexpect::session::tests::test_bash
             at src/session.rs:441
   9: <F as alloc::boxed::FnBox<A>>::call_box
             at /checkout/src/libtest/lib.rs:1449
             at /checkout/src/libcore/ops/function.rs:223
             at /checkout/src/liballoc/boxed.rs:815
  10: __rust_maybe_catch_panic
             at /checkout/src/libpanic_unwind/lib.rs:101


failures:
    session::tests::test_bash

test result: FAILED. 15 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out

error: test failed, to rerun pass '--lib'
[tjyang@fedora01 rexpect]$

```

**Comment by philippkeller** [comment]
I fixed the issue for Fedora. But the fix is now only on git and not yet on crates.io.

In order to get the fix for the time being, you can remove the `rexpect = "0.3"` dependency in Cargo.toml and instead put this:

`rexpect = { git = "https://github.com/philippkeller/rexpect" }`
